# Site settings
title: Connor Proctor
description: >
  Connor Proctor is a software engineering student studying
  computer science at UCLA.
baseurl: ""
url: "http://connorproctor.com"
excerpt_separator: <!--more-->
permalink: /posts/:title

# Build settings
markdown: kramdown
